Repository codeit-bootcamp-nodejs/2-sprint-mission, pull requests merged in 2025-09, with the labels that each got.

#146 [김진솔] sprint9
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  prisma/migrations/20250822043839_add_notify_model/migration.sql
  prisma/schema.prisma
  prisma/test.db
  src/app.ts
  src/config/db.ts
  src/controllers/article.controller.ts
  src/controllers/product.controller.ts
  src/middlewares/upload.middleware.ts
  src/repositories/article.repository.ts
  src/services/article.service.ts
  src/types/zodSchema/product.schema.ts
  src/utils/dtos/product.dto.ts
  tests/article.test.ts
  tests/auth.test.ts
  tests/product.service.test.ts
  tests/product.test.ts
  tsconfig.json
Labels: 매운맛🔥

#163 [조가현] sprint9
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/server.ts
  src/test/article.test.ts
  src/test/auth.test.ts
  src/test/product.test.ts
  src/test/setup.ts
  src/utils/db.ts
  src/utils/token.ts
Labels: 미완성🛠️, 순한맛🐑, 제출일 이후 제출한PR

#152 [권나현] sprint9
  .env.example
  .gitignore
  README.md
  jest.config.ts
  package-lock.json
  package.json
  prisma/migrations/20250526024026_init/migration.sql
  prisma/migrations/20250526054222_add_imageurl_to_product/migration.sql
  prisma/migrations/20250625132422_add_user_like_refresh/migration.sql
  prisma/migrations/20250626070711_/migration.sql
  prisma/migrations/20250628075009_add_article_image/migration.sql
  prisma/migrations/20250628110152_/migration.sql
  prisma/migrations/20250628110907_/migration.sql
  prisma/migrations/20250628111122_/migration.sql
  prisma/migrations/migration_lock.toml
  src/controllers/article.controller.ts
  src/controllers/product.controller.ts
  src/middlewares/auth.ts
  src/routes/article.router.ts
  src/routes/notification.router.ts
  src/routes/product.router.ts
  src/routes/user.router.ts
  src/tests/article.test.ts
  src/tests/auth.test.ts
  src/tests/product.test.ts
  src/tests/unit.product.service.test.ts
  src/types/express/index.d.ts
  tsconfig.json
Labels: 순한맛🐑

#156 [김수민] sprint9
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/controllers/articlesController.ts
  src/controllers/errorController.ts
  src/lib/errors/BadRequestError.ts
  src/lib/prisma/schema.prisma
  src/routers/articlesRouter.ts
  src/routers/authRouter.ts
  src/routers/productsRouter.ts
  src/services/articleService.ts
  src/services/authService.ts
  src/services/productService.ts
  src/test/article.test.ts
  src/test/auth.test.ts
  src/test/product.test.ts
  tsconfig.json
Labels: 미완성🛠️, 순한맛🐑

#150 [하상준] sprint9
  sprint03/.gitignore
  sprint03/jest.config.js
  sprint03/package-lock.json
  sprint03/package.json
  sprint03/prisma/migrations/20250825015037_/migration.sql
  sprint03/prisma/schema.prisma
  sprint03/src/app.ts
  sprint03/src/controllers/article.controller.ts
  sprint03/src/lib/db.ts
  sprint03/src/middlewares/authenticate.ts
  sprint03/src/middlewares/authorize.product.comment.ts
  sprint03/src/server.ts
  sprint03/tests/controllers/article.controller.test.ts
  sprint03/tests/controllers/product.controller.test.ts
  sprint03/tests/services/product.service.test.ts
  sprint03/tsconfig.json
Labels: 순한맛🐑
