Repository codeit-bootcamp-nodejs/2-sprint-mission, pull requests merged in 2025-06, with the labels that each got.

#33 [김진솔] sprint3
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  app.js
  dtos/araticles.dtos.js
  dtos/products.dtos.js
  error/errorHendler.js
  package-lock.json
  package.json
  prisma/migrations/20250524041959_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  routes/article.js
  routes/comment.js
  routes/product.js
  utils/db.js
Labels: 매운맛🔥

#46 [하상준] sprint3
  sprint03/.gitignore
  sprint03/bin/www
  sprint03/package-lock.json
  sprint03/package.json
  sprint03/prisma/migrations/20250526070800_add_product_table/migration.sql
  sprint03/prisma/migrations/20250527091520_article/migration.sql
  sprint03/prisma/migrations/20250528053339_comment/migration.sql
  sprint03/prisma/migrations/migration_lock.toml
  sprint03/prisma/schema.prisma
  sprint03/prisma/seed.js
  sprint03/src/app.js
  sprint03/src/controllers/article.comment.controller.js
  sprint03/src/controllers/article.controller.js
  sprint03/src/controllers/product.comment.controller.js
  sprint03/src/controllers/product.controller.js
  sprint03/src/dtos/articles.dto.js
  sprint03/src/dtos/comments.dto.js
  sprint03/src/dtos/products.dto.js
  sprint03/src/routes/articlecomments.js
  sprint03/src/routes/articles.js
  sprint03/src/routes/documents.js
  sprint03/src/routes/index.js
  sprint03/src/routes/productcomments.js
  sprint03/src/routes/products.js
  sprint03/src/utils/db.js
  sprint03/src/utils/errorHandler.js
Labels: 매운맛🔥

#41 [윤희원] sprint3
  .env
  .gitignore
  README.md
  app.js
  bin/www
  dtos/articles.dto.js
  dtos/comments.dto.js
  dtos/products.dto.js
  dtos/users.dto.js
  package-lock.json
  package.json
  prisma/migrations/20250527022925_create_user_product_article_model/migration.sql
  prisma/migrations/20250527043234_add_product_comment_article_comment_model_and_add_relation/migration.sql
  prisma/migrations/20250528043036_add_document_model/migration.sql
  prisma/migrations/20250529023808_add_tags_array_to_product/migration.sql
  prisma/migrations/20250529151356_correct_typo_mimetype/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  public/stylesheets/style.css
  routes/articleComments.js
  routes/articles.js
  routes/documents.js
  routes/index.js
  routes/productComments.js
  routes/products.js
  routes/users.js
  uploads/file-1748533647215-332311094.jpg
Labels: 순한맛🐑

#42 [김수민] sprint3
  .gitignore
  sprint1-2/ArticleService.js
  sprint1-2/ProductService.js
  sprint1-2/README.md
  sprint1-2/main.js
  sprint1-2/package-lock.json
  sprint1-2/package.json
  sprint3/README.md
  sprint3/app.js
  sprint3/bin/www
  sprint3/controllers/articlesController.js
  sprint3/controllers/commentsController.js
  sprint3/controllers/productsController.js
  sprint3/dtos/articles.dto.js
  sprint3/dtos/comments.dto.js
  sprint3/dtos/products.dto.js
  sprint3/middlwares/logger.js
  sprint3/package-lock.json
  sprint3/package.json
  sprint3/prisma/migrations/20250528082227_init/migration.sql
  sprint3/prisma/migrations/20250530035406_add_comment/migration.sql
  sprint3/prisma/migrations/20250530041119_add_document_model/migration.sql
  sprint3/prisma/migrations/migration_lock.toml
  sprint3/prisma/mock.js
  sprint3/prisma/schema.prisma
  sprint3/prisma/seed.js
  sprint3/routes/articles.js
  sprint3/routes/comments.js
  sprint3/routes/products.js
  sprint3/routes/upload.js
  sprint3/uploads/1748590893739_downloaded.jpg
  sprint3/utils/asyncHandler.js
  sprint3/utils/db.js
  sprint3/utils/validatePagination.js
Labels: 순한맛🐑

#36 [이종진] Sprint3
  .gitignore
  README.md
  package-lock.json
  package.json
  prisma/migrations/20250527005310_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.js
  src/controllers/article.controller.js
  src/controllers/comment.controller.js
  src/controllers/image.controller.js
  src/controllers/product.controller.js
  src/middlewares/errorHandler.js
  src/middlewares/upload.js
  src/middlewares/validate.js
  src/routes/article.routes.js
  src/routes/comment.routes.js
  src/routes/image.routes.js
  src/routes/product.routes.js
  src/routes/upload.routes.js
  src/seed/seed.js
  src/server.js
  uploads/1748337024860-P20180815_132404734_438A3C67-C042-440B-A817-4AB047A3C41D.PNG
  uploads/1748337916602-P20180815_132404734_438A3C67-C042-440B-A817-4AB047A3C41D.PNG
Labels: 순한맛🐑

#51 [박성국] sprint2 수정
  one/sprint1_axios/ArticleService.js
  one/sprint1_axios/ProductService.js
  one/sprint1_axios/main.js
  one/sprint1_fetch/ArticleService.js
  one/sprint1_fetch/ProductService.js
  one/sprint1_fetch/main.js
Labels: 매운맛🔥

#52 [박성국] sprint3
  README.md
  package-lock.json
  package.json
  three/.gitignore
  three/README.md
  three/bin/health.js
  three/bin/www.js
  three/dtoVerify/verifyStruct.js
  three/features/comment.js
  three/features/freeBoard.js
  three/features/imgOp.js
  three/features/usedProduct.js
  three/main/app.js
  three/package-lock.json
  three/package.json
  three/prisma/migrations/20250604055809_init/migration.sql
  three/prisma/migrations/20250606200223_migrate_for_product_tags_cascade/migration.sql
  three/prisma/migrations/20250607162617_comment_title_field_is_optional/migration.sql
  three/prisma/migrations/20250607194433_comment_delete_is_isdeleted_true/migration.sql
  three/prisma/migrations/20250608083611_comment_use_path_for_more_management/migration.sql
  three/prisma/migrations/20250608133921_reply_id_for_comment_reply/migration.sql
  three/prisma/migrations/20250608135557_comment_self_reference_setnull_to_cascade/migration.sql
  three/prisma/migrations/20250609114703_image_schema_is_added/migration.sql
  three/prisma/migrations/20250609183819_image_schema_simple_change/migration.sql
  three/prisma/migrations/20250609200052_image_schema_minor_change_originalname_unique_to_filename_unique/migration.sql
  three/prisma/migrations/migration_lock.toml
  three/prisma/schema.prisma
  three/utils/db.js
  three/utils/index.js
  three/utils/prismaErrorhandler.js
  three/utils/requests.http
  three/utils/seed.js
  three/utils/uploadTest.html
Labels: 매운맛🔥, 미완성🛠️, 제출일 이후 제출한PR
