Repository codeit-bootcamp-nodejs/2-sprint-mission, pull requests merged in 2025-07, with the labels that each got.

#63 [권나현] sprint4
  package-lock.json
  package.json
  prisma/migrations/20250625132422_add_user_like_refresh/migration.sql
  prisma/migrations/20250626070711_/migration.sql
  prisma/migrations/20250628075009_add_article_image/migration.sql
  prisma/migrations/20250628110152_/migration.sql
  prisma/migrations/20250628110907_/migration.sql
  prisma/migrations/20250628111122_/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  src/app.js
  src/controllers/article.controller.js
  src/controllers/comment.controller.js
  src/controllers/product.controller.js
  src/middlewares/auth.js
  src/middlewares/ownership.js
  src/middlewares/validation.js
  src/routes/article.routes.js
  src/routes/auth.routes.js
  src/routes/comment.routes.js
  src/routes/product.routes.js
  src/routes/user.routes.js
  src/server.js
  src/utils/token.js
Labels: 순한맛🐑

#59 [이종진] sprint4
  .gitignore
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  prisma/migrations/20250111082621_/migration.sql
  prisma/migrations/20250625021244_add_user_model/migration.sql
  prisma/migrations/20250625030822_add_user_product_relation/migration.sql
  prisma/migrations/20250625040350_add_user_article_relation/migration.sql
  prisma/migrations/20250625043246_add_user_comment_relation/migration.sql
  prisma/migrations/20250626004239_add_refresh_token_and_likes/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  public/.gitkeep
  src/controllers/articlesController.js
  src/controllers/authController.js
  src/controllers/commentsController.js
  src/controllers/errorController.js
  src/controllers/imagesController.js
  src/controllers/likesController.js
  src/controllers/productsController.js
  src/controllers/usersController.js
  src/lib/constants.js
  src/lib/errors/BadRequestError.js
  src/lib/errors/NotFoundError.js
  src/lib/prismaClient.js
  src/lib/withAsync.js
  src/main.js
  src/middlewares/articleAuthMiddleware.js
  src/middlewares/authMiddleware.js
  src/middlewares/commentAuthMiddleware.js
  src/middlewares/productAuthMiddleware.js
  src/routers/articlesRouter.js
  src/routers/authRouter.js
  src/routers/commentsRouter.js
  src/routers/imagesRouter.js
  src/routers/likesRouter.js
  src/routers/productsRouter.js
  src/routers/usersRouter.js
  src/structs/articlesStructs.js
  src/structs/authStructs.js
  src/structs/commentsStruct.js
  src/structs/commonStructs.js
  src/structs/productsStruct.js
  src/structs/usersStruct.js
  tests/test.http
  tests/test.js
  tests/test.png
Labels: 순한맛🐑

#56 [고민재] sprint4
  .gitignore
  app.js
  lib/constants.js
  lib/token.js
  middlewares/authenticate.js
  package-lock.json
  package.json
  prisma/migrations/20250625081702_user/migration.sql
  prisma/migrations/20250626082230_like_count_is_liked_update/migration.sql
  prisma/migrations/20250626094925_productlike/migration.sql
  prisma/schema.prisma
  routes/article.js
  routes/comment.js
  routes/product.js
  routes/users.js
  test.http
Labels: 매운맛🔥

#77 [권나현] sprint5
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.ts
  src/controllers/article.controller.ts
  src/controllers/comment.controller.ts
  src/controllers/product.controller.ts
  src/dtos/article.dto.ts
  src/dtos/comment.dto.ts
  src/dtos/product.dto.ts
  src/index.ts
  src/middlewares/auth.ts
  src/middlewares/ownership.ts
  src/middlewares/validation.ts
  src/repositories/article.repository.ts
  src/repositories/comment.repository.ts
  src/repositories/product.repository.ts
  src/routes/article.routes.ts
  src/routes/auth.routes.ts
  src/routes/comment.routes.ts
  src/routes/product.routes.ts
  src/routes/upload.routes.ts
  src/routes/user.routes.ts
  src/services/article.service.ts
  src/services/comment.service.ts
  src/services/product.service.ts
  src/types/express/index.d.ts
  src/utils/errorHandler.ts
  src/utils/token.ts
  test.http
  tsconfig.json
Labels: 순한맛🐑

#78 [이종진] sprint5
  .gitignore
  eslint.config.js
  package-lock.json
  package.json
  prisma/migrations/migration_lock.toml
  prisma/seed.js
  src/controllers/articlesController.ts
  src/controllers/authController.ts
  src/controllers/commentsController.ts
  src/controllers/errorController.ts
  src/controllers/imagesController.ts
  src/controllers/likesController.ts
  src/controllers/productsController.ts
  src/controllers/usersController.ts
  src/dtos/article.dto.ts
  src/dtos/auth.dto.ts
  src/dtos/comment.dto.ts
  src/dtos/image.dto.ts
  src/dtos/like.dto.ts
  src/dtos/product.dto.ts
  src/dtos/user.dto.ts
  src/lib/constants.ts
  src/lib/errors/BadRequestError.ts
  src/lib/errors/NotFoundError.ts
  src/lib/prismaClient.ts
  src/lib/withAsync.ts
  src/main.ts
  src/middlewares/articleAuthMiddleware.ts
  src/middlewares/authMiddleware.ts
  src/middlewares/commentAuthMiddleware.ts
  src/middlewares/productAuthMiddleware.ts
  src/repositories/article.repository.ts
  src/repositories/auth.repository.ts
  src/repositories/comment.repository.ts
  src/repositories/like.repository.ts
  src/repositories/product.repository.ts
  src/repositories/user.repository.ts
  src/routers/articlesRouter.ts
  src/routers/authRouter.ts
  src/routers/commentsRouter.ts
  src/routers/imagesRouter.ts
  src/routers/likesRouter.ts
  src/routers/productsRouter.ts
  src/routers/usersRouter.ts
  src/services/article.service.ts
  src/services/auth.service.ts
  src/services/comment.service.ts
  src/services/image.service.ts
  src/services/like.service.ts
  src/services/product.service.ts
  src/services/user.service.ts
  src/structs/articlesStructs.ts
  src/structs/authStructs.ts
  src/structs/commentsStruct.ts
  src/structs/commonStructs.ts
  src/structs/productsStruct.ts
  src/structs/usersStruct.ts
  tests/test.ts
  tsconfig.json
Labels: 순한맛🐑

#85 [차수연] sprint5
  mission_4/utills/auth.js
  mission_5/package-lock.json
  mission_5/package.json
  mission_5/prisma/migrations/20250523051805_first_migate/migration.sql
  mission_5/prisma/migrations/20250523073455_fix_err/migration.sql
  mission_5/prisma/migrations/20250526042409_add_article_comment/migration.sql
  mission_5/prisma/migrations/20250527054255_add_comment/migration.sql
  mission_5/prisma/migrations/20250527070811_comment_id_change/migration.sql
  mission_5/prisma/migrations/20250529011028_add_ondelete/migration.sql
  mission_5/prisma/migrations/20250625024151_/migration.sql
  mission_5/prisma/migrations/20250626010840_/migration.sql
  mission_5/prisma/migrations/20250626063903_add_liked/migration.sql
  mission_5/prisma/migrations/20250626073606_/migration.sql
  mission_5/prisma/migrations/20250711005756_/migration.sql
  mission_5/prisma/migrations/migration_lock.toml
  mission_5/prisma/schema.prisma
  mission_5/src/app.ts
  mission_5/src/controller/article-controller.ts
  mission_5/src/controller/file-controller.ts
  mission_5/src/controller/product-controller.ts
  mission_5/src/controller/user-controller.ts
  mission_5/src/lib/passport/index.ts
  mission_5/src/lib/passport/jwtStrategy.ts
  mission_5/src/lib/passport/localStrategy.ts
  mission_5/src/repository/article/article-comment-repository.ts
  mission_5/src/repository/article/article-liked-repository.ts
  mission_5/src/repository/article/article-repository.ts
  mission_5/src/repository/product/product-comment-repository.ts
  mission_5/src/repository/product/product-liked-repository.ts
  mission_5/src/repository/product/product-repository.ts
  mission_5/src/repository/user/user-repository.ts
  mission_5/src/service/article/article-comment-service.ts
  mission_5/src/service/article/article-liked-service.ts
  mission_5/src/service/article/article-service.ts
  mission_5/src/service/file/file-service.ts
  mission_5/src/service/product/product-comment-service.ts
  mission_5/src/service/product/product-liked-service.ts
  mission_5/src/service/product/product-service.ts
  mission_5/src/service/user/auth-service.ts
  mission_5/src/service/user/user-service.ts
  mission_5/src/types/article.d.ts
  mission_5/src/types/error.d.ts
  mission_5/src/types/express.d.ts
  mission_5/src/types/passport.d.ts
  mission_5/src/utills/auth.ts
  mission_5/src/utills/errorHandler.ts
  mission_5/src/utills/loginLimiter.ts
  mission_5/src/utills/prisma.ts
  mission_5/src/utills/structs.ts
  mission_5/src/utills/token.ts
  mission_5/tsconfig.json
Labels: 매운맛🔥

#101 [윤희원] sprint6
  .gitignore
  README.md
  sprint-mission-6.sql
Labels: 매운맛🔥

#126 [박성국] sprint6
  5/.gitignore
  5/solveProblems.md
  6/.gitignore
  6/solveProblems.md
  6/sprint-mission-6.sql
  7/.gitignore
  7/.vscode/settings.json
  7/RemindMe.md
  7/erd.md
  7/package-lock.json
  7/package.json
  7/prisma/schema.prisma
  7/queries.md
  7/sql/insert.sql
  7/sql/table/article.sql
  7/sql/table/article_comment.sql
  7/sql/table/article_like.sql
  7/sql/table/client.sql
  7/sql/table/image.sql
  7/sql/table/product.sql
  7/sql/table/product_comment.sql
  7/sql/table/product_like.sql
  7/sql/table/product_tag.sql
  7/sql/table/tag.sql
  7/sql/trigger/update_timestamp.sql
  7/src/create_tables.ts
  7/src/delete_data.ts
  7/src/drop_tables.ts
  7/src/insert_data.ts
  7/src/utils/readSQL.ts
  7/src/utils/sql_python/make_insert_data.py
  7/src/utils/sql_python/requirements.txt
  7/tsconfig.json
Labels: 매운맛🔥, 제출일 이후 제출한PR
